steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/shinyapps:latest || exit 0']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', 
         '-t', 'gcr.io/${PROJECT_ID}/shinyapps', 
         '--cache-from', 'gcr.io/$PROJECT_ID/shinyapps:latest',
         '.']
timeout: 3600s
images: ['gcr.io/${PROJECT_ID}/shinyapps:latest']

